### ISSUE TITLE
How to run the snakemake script on my linux machine?

### ISSUE THREAD

**Issue by worsteggs** [cgob/codonDT_snakemake#2]
Hello, Cédric,
First, thanks for your nice work.
I want to run this script on my contos machine, but I can't run it successfully.
First, I download this repo by `gh repo clone cgob/codonDT_snakemake` and simply run the file `running_command.sh`.
But error occurred:
```sbatch: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host
sbatch: error: fetch_config: DNS SRV lookup failed
sbatch: error: _establish_config_source: failed to fetch config
sbatch: fatal: Could not establish a configuration source
```
It's there anything I missed? Looking for your help.
Tanks again!

Eggs

**Comment by cgob** [comment]
Hi Eggs,
Thanks a lot for your comment. Sorry for the late reply, I didn't get the notification.
The pipeline was made to run on HPC cluster (with SLURM scheduler) due to the large RAM memory required. Do you have access to a HPC cluster?

Best,
Cédric

**Comment by worsteggs** [comment]
> Hi Eggs,
> Thanks a lot for your comment. Sorry for the late reply, I didn't get the notification.
> The pipeline was made to run on HPC cluster (with SLURM scheduler) due to the large RAM memory required. Do you have access to a HPC cluster?
> 
> Best,
> Cédric

Thanks for your reply, Cédric @cgob .
Sorry for telling you that I have no access to an HPC cluster for now. But I think my using machine should be enough for a single sample, because it has about 1T RAM and 96 core.
So I know it is better to use an HPC cluster. But if it's possible to use a nice liunx machine to run the snakemake script? I think just run the simple command in the script might be work.
I hope to get your nice reply.

Sincerely，
Eggs

**Comment by cgob** [comment]
Hi,
Indeed your configuration is more than enough to run the pipeline. You can simply run it using the snakemake command and not the running_command.sh which sends slurm jobs.
` snakemake -n` for a dry-run in the snakefile repository.
Be sure to have all the dependencies installed and modify the paths accordingly in the snakefile:

- samtools
- STAR
- fastq-dump from sra-toolkit
- R with all the required packages
- Perl
I will try to improve and automatize the installation of the required software and packages as I just realised it's not very efficient at the moment.
Best,
Cédric

**Comment by worsteggs** [comment]
OK, I see that is a solution.
I've tried to run `snakemake -n` with all the dependencies load in my PATH. Then an error occur `ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'gcc/7.4.0'`.
In the Snakefile, I found the shell command lines have 'module' like `module load gcc/7.4.0; module load star/2.7.0e`. 
Since I never used such 'module' command or software, so was it necessary for using 'module' to run the script? And where can I get the modulefile to run the Snakefile for I didn't find such modulefile in this repo?
I hope I have not disturbed you for my so many questions.

yours,
Eggs

**Comment by cgob** [comment]
Don't worry with the questions, I'm happy to help and make this pipeline useful for someone else.
Yes you should remove any line with "module load" as it is specific to our cluster and you will define the software path specifically for your setup.

**Comment by worsteggs** [comment]
@cgob , thanks for your replying and useful help!
Now, I think I have done with this issue, so I will close it.
And please let me know if you have any recommendation.

Best regards,
Eggs
