### ISSUE TITLE
Makefit.R RNA error

### ISSUE THREAD

**Issue by quarkaffi** [cgob/codonDT_snakemake#5]
Hi,

I am having some troubles running the Makefit.R script on my RNA seq samples. I have 75 bp reads and when I used the the standard length filter preset in the config.yaml it would not create any count files for my RNA samples. This I could fix by setting the upper limit (L2) to 75, which I already found a little odd. Shouldn't be the read length filter only be relevant to the Riboseq files? Do I have to do something to my RNA reads before feeding them into the pipeline, or am I just missing something?

Makefit.R is then throwing this error:

Error in validObject(.Object) : 
  invalid class “dsparseModelMatrix” object: superclass "Mnumeric" not defined in the environment of the object's class
Calls: MakeFit ... initialize -> callNextMethod -> .nextMethod -> validObject
Execution halted

The RIBO files alone run through without a problem.

Thank you for your help!

**Comment by quarkaffi** [comment]
The mistake was on my side (as expected). It was a shell issue. Now it runs smoothly.

**Comment by quarkaffi** [comment]
I think I have figured out now why Makefit.R was giving an error. It is due to the r-matrix version that was used. The latest version (1.3-4) seems to give some troubles. I downgraded it now to 1.3-0 and so far it is running an the error did not reappear yet.

**Comment by cgob** [comment]
Hello,

Thanks a lot for your message and feedback.
I will have look at your issue asap (someone else contacted me with the same error). I will correct it and I will try to update the conda environment with the right version of r-matrix.  Please don't hesitate to ask if you have more questions. 

Best,
 
Cédric

**Comment by quarkaffi** [comment]
Hi Cedric,

thanks for the reply. Indeed, I ran into another problem that was also discussed in a separate open issue. While running the pipeline, the Makefit.R now gave me another error for my RNA samples (both exited with the same message). The RNA samples are not incredibly deep sequenced but with 20M-30M reads they are also not at the very low end. My riboseq files are a lot deeper with roughly 90M uniquely mapped reads. Is that error coming from lacking depth?  

`Error in IRLS(lp, control) : 
Number of iterations exceeded maximum MXITER = 400
Calls: MakeFit -> glm4 -> fitGlm4 -> IRLS
Execution halted`

Or is it rather from the issue before that I was mentioning with the RNAseq readlength being 75 bp and that I had to put L2 to 75 to even get count files?

Best,
Martin

**Comment by quarkaffi** [comment]
Hi Cedric,

Another very simple solution. I saw in the code that the E P A sites are taken from the riboseq data and used for the RNAseq for the fit. As there were no values for the large reads (anything above 40), I manually copied now the offsets calculated for 28 length (the dominant species for my riboseq) in the Riboseq to the 75 length as a test and now it seems to run. Just to doublecheck: Is that okay what I did there? As I understood it, the RNA fit is just to normalize for any library prep bias, so my approach should be okay right?

Best,
Martin

**Comment by cgob** [comment]
Hi Martin,
Thanks for your feedback. It is important to note that normalisation by the RNA-seq is relevant and will attenuate the biases at read extremities only if both the ribosome profiling and RNA-seq data share the same read size distribution and library preparation method. This explains why I haven't implemented an offset for the RNA-seq if the read size distributions are different and that they share the same L1/L2 parameters. Nevertheless, normalization by RNA-seq also allows to express the translation flux per mRNA abundance as an improvement of the commonly used  “translation efficiency” parameter. 
Your workaround could be ok if you are interested in flux per mRNA but be aware that it will not reduce the bias, and that increasing L2 will blur the result of your ribosome profiling data.

Best,

Cédric

**Comment by quarkaffi** [comment]
Oh, I see. So the problem all along was that the RNAseq library read distribution is too disimilar to the Riboseq data. So is it probably better to just run the Riboseq data without RNAseq, and instead use stricter length filters? What would you recommend?

**Comment by quarkaffi** [comment]
Hi Cedric,

You basically already gave the answer in your last reply. So I am closing this now. I decided now that I won't normalize to RNAseq and use a stricter L1 and L2. As I am anyway more interested in the change between 2 conditions and libraries were prepared at the exact same time, I expect to have the same biases between the 2 which then cancel each other out. Thank you for all the help in that matter!

Best,
Martin
